const { Key } = require('./key');
const { Row } = require('./row');
const { Keyboard } = require('./keyboard');

const keyboard = new Keyboard([
  new Row([
    new Key({
      ru: 'ё',
      en: '`',
    }, {
      ru: 'ё',
      en: '`',
    }, {
      ru: 'Ё',
      en: '~',
    }, {
      ru: true,
      en: false,
    }, 'Backquote', 'small'),
    new Key({
      ru: '1',
      en: '1',
    }, {
      ru: '1',
      en: '1',
    }, {
      ru: '!',
      en: '!',
    }, {
      ru: false,
      en: false,
    }, 'Digit1', 'small'),
    new Key({
      ru: '2',
      en: '2',
    }, {
      ru: '2',
      en: '2',
    }, {
      ru: '"',
      en: '@',
    }, {
      ru: false,
      en: false,
    }, 'Digit2', 'small'),
    new Key({
      ru: '3',
      en: '3',
    }, {
      ru: '3',
      en: '3',
    }, {
      ru: '№',
      en: '#',
    }, {
      ru: false,
      en: false,
    }, 'Digit3', 'small'),
    new Key({
      ru: '4',
      en: '4',
    }, {
      ru: '4',
      en: '4',
    }, {
      ru: ';',
      en: '$',
    }, {
      ru: false,
      en: false,
    }, 'Digit4', 'small'),
    new Key({
      ru: '5',
      en: '5',
    }, {
      ru: '5',
      en: '5',
    }, {
      ru: '%',
      en: '%',
    }, {
      ru: false,
      en: false,
    }, 'Digit5', 'small'),
    new Key({
      ru: '6',
      en: '6',
    }, {
      ru: '6',
      en: '6',
    }, {
      ru: ':',
      en: '^',
    }, {
      ru: false,
      en: false,
    }, 'Digit6', 'small'),
    new Key({
      ru: '7',
      en: '7',
    }, {
      ru: '7',
      en: '7',
    }, {
      ru: '?',
      en: '&',
    }, {
      ru: false,
      en: false,
    }, 'Digit7', 'small'),
    new Key({
      ru: '8',
      en: '8',
    }, {
      ru: '8',
      en: '8',
    }, {
      ru: '*',
      en: '*',
    }, {
      ru: false,
      en: false,
    }, 'Digit8', 'small'),
    new Key({
      ru: '9',
      en: '9',
    }, {
      ru: '9',
      en: '9',
    }, {
      ru: '(',
      en: '(',
    }, {
      ru: false,
      en: false,
    }, 'Digit9', 'small'),
    new Key({
      ru: '0',
      en: '0',
    }, {
      ru: '0',
      en: '0',
    }, {
      ru: ')',
      en: ')',
    }, {
      ru: false,
      en: false,
    }, 'Digit0', 'small'),
    new Key({
      ru: '-',
      en: '-',
    }, {
      ru: '-',
      en: '-',
    }, {
      ru: '_',
      en: '_',
    }, {
      ru: false,
      en: false,
    }, 'Minus', 'small'),
    new Key({
      ru: '=',
      en: '=',
    }, {
      ru: '=',
      en: '=',
    }, {
      ru: '+',
      en: '+',
    }, {
      ru: false,
      en: false,
    }, 'Equal', 'small'),
    new Key({
      ru: 'Backspace',
      en: 'Backspace',
    }, {
      ru: '\b',
      en: '\b',
    }, {
      ru: '\b',
      en: '\b',
    }, {
      ru: false,
      en: false,
    }, 'Backspace'),
  ]),
  new Row([
    new Key({
      ru: 'Tab',
      en: 'Tab',
    }, {
      ru: '\t',
      en: '\t',
    }, {
      ru: '\t',
      en: '\t',
    }, {
      ru: false,
      en: false,
    }, 'Tab'),
    new Key({
      ru: 'Й',
      en: 'Q',
    }, {
      ru: 'й',
      en: 'q',
    }, {
      ru: 'Й',
      en: 'Q',
    }, {
      ru: true,
      en: true,
    }, 'KeyQ', 'small'),
    new Key({
      ru: 'Ц',
      en: 'W',
    }, {
      ru: 'ц',
      en: 'w',
    }, {
      ru: 'Ц',
      en: 'W',
    }, {
      ru: true,
      en: true,
    }, 'KeyW', 'small'),
    new Key({
      ru: 'У',
      en: 'E',
    }, {
      ru: 'у',
      en: 'e',
    }, {
      ru: 'У',
      en: 'E',
    }, {
      ru: true,
      en: true,
    }, 'KeyE', 'small'),
    new Key({
      ru: 'К',
      en: 'R',
    }, {
      ru: 'к',
      en: 'r',
    }, {
      ru: 'К',
      en: 'R',
    }, {
      ru: true,
      en: true,
    }, 'KeyR', 'small'),
    new Key({
      ru: 'Е',
      en: 'T',
    }, {
      ru: 'е',
      en: 't',
    }, {
      ru: 'Е',
      en: 'T',
    }, {
      ru: true,
      en: true,
    }, 'KeyT', 'small'),
    new Key({
      ru: 'Н',
      en: 'Y',
    }, {
      ru: 'н',
      en: 'y',
    }, {
      ru: 'Н',
      en: 'Y',
    }, {
      ru: true,
      en: true,
    }, 'KeyY', 'small'),
    new Key({
      ru: 'Г',
      en: 'U',
    }, {
      ru: 'г',
      en: 'u',
    }, {
      ru: 'Г',
      en: 'U',
    }, {
      ru: true,
      en: true,
    }, 'KeyU', 'small'),
    new Key({
      ru: 'Ш',
      en: 'I',
    }, {
      ru: 'ш',
      en: 'i',
    }, {
      ru: 'Ш',
      en: 'I',
    }, {
      ru: true,
      en: true,
    }, 'KeyI', 'small'),
    new Key({
      ru: 'Щ',
      en: 'O',
    }, {
      ru: 'щ',
      en: 'o',
    }, {
      ru: 'Щ',
      en: 'O',
    }, {
      ru: true,
      en: true,
    }, 'KeyO', 'small'),
    new Key({
      ru: 'З',
      en: 'P',
    }, {
      ru: 'з',
      en: 'p',
    }, {
      ru: 'З',
      en: 'P',
    }, {
      ru: true,
      en: true,
    }, 'KeyP', 'small'),
    new Key({
      ru: 'X',
      en: '[',
    }, {
      ru: 'х',
      en: '[',
    }, {
      ru: 'Х',
      en: '{',
    }, {
      ru: true,
      en: false,
    }, 'BracketLeft', 'small'),
    new Key({
      ru: 'Ъ',
      en: ']',
    }, {
      ru: 'ъ',
      en: ']',
    }, {
      ru: 'Ъ',
      en: '}',
    }, {
      ru: true,
      en: false,
    }, 'BracketRight', 'small'),
    new Key({
      ru: '\\',
      en: '\\',
    }, {
      ru: '\\',
      en: '\\',
    }, {
      ru: '/',
      en: '|',
    }, {
      ru: false,
      en: false,
    }, 'Backslash', 'small'),
    new Key({
      ru: 'Delete',
      en: 'Delete',
    }, {
      ru: '\x7f',
      en: '\x7f',
    }, {
      ru: '\x7f',
      en: '\x7f',
    }, {
      ru: false,
      en: false,
    }, 'Delete'),
  ]),
  new Row([
    new Key({
      ru: 'Caps Lock',
      en: 'Caps Lock',
    }, {
      ru: '',
      en: '',
    }, {
      ru: '',
      en: '',
    }, {
      ru: false,
      en: false,
    }, 'CapsLock', 'caps-lock-btn'),
    new Key({
      ru: 'Ф',
      en: 'A',
    }, {
      ru: 'ф',
      en: 'a',
    }, {
      ru: 'Ф',
      en: 'A',
    }, {
      ru: true,
      en: true,
    }, 'KeyA', 'small'),
    new Key({
      ru: 'Ы',
      en: 'S',
    }, {
      ru: 'ы',
      en: 's',
    }, {
      ru: 'Ы',
      en: 'S',
    }, {
      ru: true,
      en: true,
    }, 'KeyS', 'small'),
    new Key({
      ru: 'В',
      en: 'D',
    }, {
      ru: 'в',
      en: 'd',
    }, {
      ru: 'В',
      en: 'D',
    }, {
      ru: true,
      en: true,
    }, 'KeyD', 'small'),
    new Key({
      ru: 'А',
      en: 'F',
    }, {
      ru: 'а',
      en: 'f',
    }, {
      ru: 'А',
      en: 'F',
    }, {
      ru: true,
      en: true,
    }, 'KeyF', 'small'),
    new Key({
      ru: 'П',
      en: 'G',
    }, {
      ru: 'п',
      en: 'g',
    }, {
      ru: 'П',
      en: 'G',
    }, {
      ru: true,
      en: true,
    }, 'KeyG', 'small'),
    new Key({
      ru: 'Р',
      en: 'H',
    }, {
      ru: 'р',
      en: 'h',
    }, {
      ru: 'Р',
      en: 'H',
    }, {
      ru: true,
      en: true,
    }, 'KeyH', 'small'),
    new Key({
      ru: 'О',
      en: 'J',
    }, {
      ru: 'о',
      en: 'j',
    }, {
      ru: 'О',
      en: 'J',
    }, {
      ru: true,
      en: true,
    }, 'KeyJ', 'small'),
    new Key({
      ru: 'Л',
      en: 'K',
    }, {
      ru: 'л',
      en: 'k',
    }, {
      ru: 'Л',
      en: 'K',
    }, {
      ru: true,
      en: true,
    }, 'KeyK', 'small'),
    new Key({
      ru: 'Д',
      en: 'L',
    }, {
      ru: 'д',
      en: 'l',
    }, {
      ru: 'Д',
      en: 'L',
    }, {
      ru: true,
      en: true,
    }, 'KeyL', 'small'),
    new Key({
      ru: 'Ж',
      en: ';',
    }, {
      ru: 'ж',
      en: ';',
    }, {
      ru: 'Ж',
      en: ':',
    }, {
      ru: true,
      en: false,
    }, 'Semicolon', 'small'),
    new Key({
      ru: 'Э',
      en: '\'',
    }, {
      ru: 'э',
      en: '\'',
    }, {
      ru: 'Э',
      en: '"',
    }, {
      ru: true,
      en: false,
    }, 'Quote', 'small'),
    new Key({
      ru: 'Enter',
      en: 'Enter',
    }, {
      ru: '\n',
      en: '\n',
    }, {
      ru: '\n',
      en: '\n',
    }, {
      ru: false,
      en: false,
    }, 'Enter'),
  ]),
  new Row([
    new Key({
      ru: 'Shift',
      en: 'Shift',
    }, {
      ru: '',
      en: '',
    }, {
      ru: '',
      en: '',
    }, {
      ru: false,
      en: false,
    }, 'ShiftLeft'),
    new Key({
      ru: 'Я',
      en: 'Z',
    }, {
      ru: 'я',
      en: 'z',
    }, {
      ru: 'Я',
      en: 'Z',
    }, {
      ru: true,
      en: true,
    }, 'KeyZ', 'small'),
    new Key({
      ru: 'Ч',
      en: 'X',
    }, {
      ru: 'ч',
      en: 'x',
    }, {
      ru: 'Ч',
      en: 'X',
    }, {
      ru: true,
      en: true,
    }, 'KeyX', 'small'),
    new Key({
      ru: 'С',
      en: 'C',
    }, {
      ru: 'с',
      en: 'c',
    }, {
      ru: 'С',
      en: 'C',
    }, {
      ru: true,
      en: true,
    }, 'KeyC', 'small'),
    new Key({
      ru: 'М',
      en: 'V',
    }, {
      ru: 'м',
      en: 'v',
    }, {
      ru: 'М',
      en: 'V',
    }, {
      ru: true,
      en: true,
    }, 'KeyV', 'small'),
    new Key({
      ru: 'И',
      en: 'B',
    }, {
      ru: 'и',
      en: 'b',
    }, {
      ru: 'И',
      en: 'B',
    }, {
      ru: true,
      en: true,
    }, 'KeyB', 'small'),
    new Key({
      ru: 'Т',
      en: 'N',
    }, {
      ru: 'т',
      en: 'n',
    }, {
      ru: 'Т',
      en: 'N',
    }, {
      ru: true,
      en: true,
    }, 'KeyN', 'small'),
    new Key({
      ru: 'Ь',
      en: 'M',
    }, {
      ru: 'ь',
      en: 'm',
    }, {
      ru: 'Ь',
      en: 'M',
    }, {
      ru: true,
      en: true,
    }, 'KeyM', 'small'),
    new Key({
      ru: 'Б',
      en: ',',
    }, {
      ru: 'б',
      en: ',',
    }, {
      ru: 'Б',
      en: '<',
    }, {
      ru: true,
      en: false,
    }, 'Comma', 'small'),
    new Key({
      ru: 'Ю',
      en: '.',
    }, {
      ru: 'ю',
      en: '.',
    }, {
      ru: 'Ю',
      en: '>',
    }, {
      ru: true,
      en: false,
    }, 'Period', 'small'),
    new Key({
      ru: '.',
      en: '/',
    }, {
      ru: '.',
      en: '/',
    }, {
      ru: '.',
      en: '?',
    }, {
      ru: false,
      en: false,
    }, 'Slash', 'small'),
    new Key({
      ru: '↑',
      en: '↑',
    }, {
      ru: '↑',
      en: '↑',
    }, {
      ru: '↑',
      en: '↑',
    }, {
      ru: false,
      en: false,
    }, 'ArrowUp', 'small'),
    new Key({
      ru: 'Shift',
      en: 'Shift',
    }, {
      ru: '',
      en: '',
    }, {
      ru: '',
      en: '',
    }, {
      ru: false,
      en: false,
    }, 'ShiftRight', 'small'),
  ]),
  new Row([
    new Key({
      ru: 'Ctrl',
      en: 'Ctrl',
    }, {
      ru: '',
      en: '',
    }, {
      ru: '',
      en: '',
    }, {
      ru: false,
      en: false,
    }, 'ControlLeft'),
    new Key({
      ru: 'Win',
      en: 'Win',
    }, {
      ru: '',
      en: '',
    }, {
      ru: '',
      en: '',
    }, {
      ru: false,
      en: false,
    }, 'Super', 'small'),
    new Key({
      ru: 'Alt',
      en: 'Alt',
    }, {
      ru: '',
      en: '',
    }, {
      ru: '',
      en: '',
    }, {
      ru: false,
      en: false,
    }, 'AltLeft', 'small'),
    new Key({
      ru: 'Пробел',
      en: 'Space',
    }, {
      ru: ' ',
      en: ' ',
    }, {
      ru: ' ',
      en: ' ',
    }, {
      ru: false,
      en: false,
    }, 'Space', 'space'),
    new Key({
      ru: 'Alt',
      en: 'Alt',
    }, {
      ru: '',
      en: '',
    }, {
      ru: '',
      en: '',
    }, {
      ru: false,
      en: false,
    }, 'AltRight', 'small'),
    new Key({
      ru: 'Ctrl',
      en: 'Ctrl',
    }, {
      ru: '',
      en: '',
    }, {
      ru: '',
      en: '',
    }, {
      ru: false,
      en: false,
    }, 'ControlRight'),
    new Key({
      ru: '←',
      en: '←',
    }, {
      ru: '←',
      en: '←',
    }, {
      ru: '←',
      en: '←',
    }, {
      ru: false,
      en: false,
    }, 'ArrowLeft', 'small'),
    new Key({
      ru: '↓',
      en: '↓',
    }, {
      ru: '↓',
      en: '↓',
    }, {
      ru: '↓',
      en: '↓',
    }, {
      ru: false,
      en: false,
    }, 'ArrowDown', 'small'),
    new Key({
      ru: '→',
      en: '→',
    }, {
      ru: '→',
      en: '→',
    }, {
      ru: '→',
      en: '→',
    }, {
      ru: false,
      en: false,
    }, 'ArrowRight', 'small'),
  ]),
]);

module.exports = {
  keyboard,
};
